Models/Actor.cs
namespace DapperSW.Models
{
    public class Actor
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }
}

Models/Category.cs
namespace DapperSW.Models
{
    public class Category
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

Models/Film.cs
namespace DapperSW.Models
{
    public class Film
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int ReleaseYear { get; set; }
        public string Rating { get; set; }
        public string Spoilers { get; set; }
    }
}

ViewModels/FilmDetails.cs
using System.Collections.Generic;
using DapperSW.Models;

namespace DapperSW.ViewModels
{
    public class FilmDetails
    {
        public string Title { get; set; }
        public string Description { get; set; }
        public int ReleaseYear { get; set; }
        public string Rating { get; set; }

        public List<Actor> Actors { get; set;}
        public List<Category> Categories { get; set;}
    }
}

Controllers/FilmController.cs
using DapperSW.Models;
using Microsoft.AspNetCore.Mvc;
using Dapper;
using Microsoft.Extensions.Options;
using Npgsql;
using System.Collections.Generic;
using DapperSW.ViewModels;
using System.Linq;

namespace DapperSW.Controllers
{
    public class FilmController : Controller
    {
        private MySettings _settings;
        public FilmController(IOptions<MySettings> settings)
        {
            _settings = settings.Value;
        }

        public IActionResult Index()
        {
            var sql = @"
            SELECT
                film_id as id, 
                title,
                description
            FROM film
            ORDER BY random() LIMIT {=limit}";
            IEnumerable<Film> results;
            using (var connection = new NpgsqlConnection(_settings.ConnectionString))
            {
                results = connection.Query<Film>(sql, new { limit = 10 });
            }
            return View(results);
        }

        public IActionResult Details(int id)
        {
            var sql = @"
            SELECT
                title,
                description,
                cast(release_year as int) as releaseyear,
                cast(rating as text) as rating
            FROM film
            WHERE film_id = @id;
            
            SELECT
                a.first_name,
                a.last_name
            FROM actor a
                INNER JOIN film_actor fa
                    ON a.actor_id = fa.actor_id
            WHERE fa.film_id = @id;

            SELECT
                c.name
            FROM category c
                INNER JOIN film_category fc
                    ON c.category_id = fc.category_id
            WHERE fc.film_id = @id";
            FilmDetails results = new FilmDetails();
            using (var connection = new NpgsqlConnection(_settings.ConnectionString))
            {
                Dapper.DefaultTypeMap.MatchNamesWithUnderscores = true;
                using (var multi = connection.QueryMultiple(sql, new { @id = id} )) {
                    results = multi.Read<FilmDetails>().Single();
                    results.Actors = multi.Read<Actor>().ToList();
                    results.Categories = multi.Read<Category>().ToList();
                }
            }
            return View(results);
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

Controllers/FilmCrapController.cs
using DapperSW.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Npgsql;
using System.Collections.Generic;
using System.Linq;
using System;

namespace DapperSW.Controllers
{
    public class FilmCrapController : Controller
    {
        private MySettings _settings;
        public FilmCrapController(IOptions<MySettings> settings)
        {
            _settings = settings.Value;
        }
        public IActionResult Index()
        {
            var sql = @"Select film_id, title, description
            FROM film
            ORDER BY random() LIMIT @limit";
            List<Film> results = new List<Film>();

            var con = new NpgsqlConnection(_settings.ConnectionString);
            con.Open();
            NpgsqlCommand cmd = new NpgsqlCommand(sql);
            cmd.Connection = con;

            cmd.Parameters.Add("@limit", NpgsqlTypes.NpgsqlDbType.Integer).Value = 10;

            NpgsqlDataReader rdr = cmd.ExecuteReader();
            while (rdr.Read())
            {
                results.Add(new Film
                {
                    Id = Convert.ToInt32(rdr["film_id"]),
                    Title = rdr["title"].ToString(),
                    Description = rdr["description"].ToString()
                });
            }
            return View(results.AsEnumerable());
        }


        public IActionResult Error()
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace DapperSW.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

Views/Film/Details.cshtml
@model DapperSW.ViewModels.FilmDetails
@{
    ViewData["Title"] = "Film Details";
}

<div class="ui raised very padded text container segment">
    @Html.ActionLink("Back to list", "Index", "Film", new {}, new { @class = "ui basic button" })
    
    <h1 class="ui center aligned icon header">
        <i class="circular film icon"></i>
        @Model.Title (@Model.ReleaseYear)
    </h1>

    <div class="description massive">
        <p>@Model.Description</p>
        <div class="ui grey label">
            Rating
            <div class=" detail">@Model.Rating</div>
        </div>

        <div class="ui horizontal segments">
            <div class="ui segment">
                <h2 class="ui header">Categories</h2>
                @foreach (var category in Model.Categories) {
                    <a class="ui blue tag label">@category.Name</a>
                }
            </div>

            <div class="ui segment">
                <h2 class="ui header">Starring</h2>
                <div class="ui list">
                @foreach (var actor in Model.Actors) {
                    <div class="item">
                        <i class="star icon"></i>
                        <div class="content">
                            @actor.FirstName @actor.LastName
                        </div>
                    </div>
                }
                </div>
            </div>
        </div>
    </div>
</div>

Views/Film/Index.cshtml
@model IEnumerable<DapperSW.Models.Film>
@{
    ViewData["Title"] = "Film List";
}
<div class="ui content">
<h1 class="ui icon header">
  <i class="circular film icon"></i>
  Film Overview
</h1>

</div>

<div class="ui raised text segment">
    <h1 class="ui black ribbon label">Random Selector</h1>
    <ol class="ui animated selection list">
        @foreach (var film in Model) {
            <li class="item">
                <div class="header">@Html.ActionLink(@film.Title, "Details", "Film", new { id = @film.Id })</div>
                @film.Description
            </li>
        }
    </ol>
</div>

Views/FilmCrap/Index.cshtml
@model IEnumerable<DapperSW.Models.Film>
@{
    ViewData["Title"] = "Film List";
}
<div class="ui content">
<h1 class="ui icon header">
  <i class="circular film icon"></i>
  Film Overview
</h1>

</div>

<div class="ui raised text segment">
    <h1 class="ui black ribbon label">Random Selector</h1>
    <ol class="ui animated selection list">
        @foreach (var film in Model) {
            <li class="item">
                <div class="header">@film.Title</div>
                @film.Description
            </li>
        }
    </ol>
</div>

Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}

<div class="ui container">
    <h2>@ViewData["Title"].</h2>
    <h3>@ViewData["Message"]</h3>

    <p>Use this area to provide additional information.</p> 
</div>

Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<div class="ui container">
    <h2>@ViewData["Title"]</h2>
    <h3>@ViewData["Message"]</h3>
    <address>
        One Microsoft Way<br/>
        Redmond, WA 98052-6399<br/>
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}


<div class="ui blue inverted vertical masthead center aligned segment">

    <div class="ui text container">

        <h1 class="ui inverted header">
            MVC + Semantic UI
        </h1>
        <h2>If you build it, they will come.</h2>
        <a class="ui huge secondary button" href="http://semantic-ui.com/">
            Get Started <i class="right arrow icon"></i>
        </a>
    </div>

</div>
<div class="ui grid">
    <div class="eight wide column">
        <div class="ui segment">
            <h1 class="ui black ribbon label">How To</h1>
            <ol class="ui list">
                <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
                <li><a href="https://go.microsoft.com/fwlink/?LinkID=699314">Add an appsetting in config and access it in app.</a></li>
                <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
                <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
                <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
                <li><a href="https://go.microsoft.com/fwlink/?LinkId=699318">Add client packages using Bower.</a></li>
                <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
            </ol>
        </div>
    </div>
    <div class="eight wide column">
        <div class="ui segment">
            <h1 class="ui black ribbon label">Overview</h1>
            <ol class="ui list">
                <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET 5</a></li>
                <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET 5 such as Startup and middleware.</a></li>
                <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
                <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
                <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
                <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
                <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
            </ol>
        </div>
    </div>

</div>
<div class="ui grid">

    <div class="eight wide column">
        <div class="ui segment">
            <h1 class="ui black ribbon label">Run & Deploy</h1>
            <ol class="ui list">
                <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
                <li><a href="https://go.microsoft.com/fwlink/?LinkID=517852">Run your app on .NET Core</a></li>
                <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run commands in your project.json</a></li>
                <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
            </ol>
        </div>
    </div>
    <div class="eight wide column">
        <div class="ui segment">
            <h1 class="ui black ribbon label">Application Uses</h1>
            <ol class="left aligned ui list">
                <li>Sample pages using ASP.NET MVC 6</li>
                <li><a href="https://go.microsoft.com/fwlink/?LinkId=518007">Gulp</a> and <a href="https://go.microsoft.com/fwlink/?LinkId=518004">Bower</a> for managing client-side libraries</li>
                <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
            </ol>
        </div>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <title>@ViewData["Title"] - DapperSW</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/semantic/dist/semantic.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://oss.maxcdn.com/semantic-ui/2.1.8/semantic.min.css"
              asp-fallback-href="~/lib/semantic/dist/semantic.min.css"
              asp-fallback-test-class="ui button" asp-fallback-test-property="cursor" asp-fallback-test-value="pointer" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <!-- Following Menu -->
    <div class="ui large top pointing fixed menu">
        <div class="ui container">
            <a class="toc item">
                <i class="sidebar icon"></i>
                <span class="sr-only">Toggle Navigation</span>
            </a>
            <a href="/" class="header item">DapperSW</a>
            <menulink class="blue item" asp-area="" controller-name="Home" action-name="Index" menu-text="Home"></menulink>
            <menulink class="blue item" asp-area="" controller-name="Home" action-name="About" menu-text="About"></menulink>
            <menulink class="blue item" asp-area="" controller-name="Home" action-name="Contact" menu-text="Contact">Contact</menulink>
            <menulink class="blue item" asp-area="" controller-name="FilmCrap" action-name="Index" menu-text="Crap Films"></menulink>
            <menulink class="blue item" asp-area="" controller-name="Film" action-name="Index" menu-text="Nice Films"></menulink>

        </div>
    </div>

    <!-- Sidebar Menu -->
    <div class="ui vertical inverted sidebar menu">
        <menulink class="blue item" asp-area="" controller-name="Home" action-name="Index" menu-text="Home"></menulink>
        <menulink class="blue item" asp-area="" controller-name="Home" action-name="About" menu-text="About"></menulink>
        <menulink class="blue item" asp-area="" controller-name="Home" action-name="Contact" menu-text="Contact"></menulink>
        <menulink class="blue item" asp-area="" controller-name="FilmCrap" action-name="Index" menu-text="Crap Films"></menulink>
        <menulink class="blue item" asp-area="" controller-name="Film" action-name="Index" menu-text="Nice Films"></menulink>
    </div>

    <!-- Page Contents -->
    <div class="pusher">
        <div class="ui container content">
            @RenderBody()
        </div>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/semantic/dist/semantic.js"></script>
        <script src="~/js/site.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.3.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://oss.maxcdn.com/semantic-ui/2.1.8/semantic.min.js"
                asp-fallback-src="~/lib/semantic/dist/semantic.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>